require 'testbed/base'
require 'testbed/hardcode_testbed'
require 'testbed/send_testbed'
require 'testbed/send_table_testbed'
require 'testbed/bind_table_testbed'
require 'testbed/code_gen_testbed'
require 'testbed/if_code_gen_testbed'
require 'testbed/lambda_table_testbed'
